### ISSUE TITLE
🐛 Bug Report: "short links" should redirect, not show the post

### ISSUE THREAD

**Issue by shruuub** [libreddit/ferrit#38]
## Describe the bug

Short "post ids" (such as fcahsd) get crawled by search engines. Of course you could change the robots.txt to disallow all, however, I personally don't like that. On reddit (reddit.com/fcahsd), these ids simply get redirected to the full url (https://www.reddit.com/r/siemreap/comments/fcahsd/big_discount_for_angkor_wat_ticket/) Thus, it wouldn't mess up search results, since /r/* can be blocked by robots.txt.

Interestingly, curling the instance, it does actually return a 404, whilst still displaying the post.
## Steps to reproduce the bug
1.Have an instance running for a few days
2. Search for site:ferrit.example.org ( of course replacing that with your instance)
3. Usually clicking on the 1st/2nd link

## What's the expected behavior?
I should simply redirect to the "actual" post.

## Additional context / screenshot
![screenshot_search](https://user-images.githubusercontent.com/77551497/195971246-e06f933c-5b5d-4130-a1d0-e7b2bd4f4451.PNG)

![screenshot_curl](https://user-images.githubusercontent.com/77551497/195971782-2e5cd6c1-dce6-4921-8ad1-a714119bb89b.PNG)

**Comment by B0pol** [comment]
IMO it should not only be short links but all duplicate links. For posts, there is also `/comments/:id`, and more https://github.com/ferritreader/ferrit/blob/3a6b76374e898cbef711ada86cca7328ddbfac65/src/main.rs#L239-L246

there is a similar thing for users https://github.com/ferritreader/ferrit/blob/3a6b76374e898cbef711ada86cca7328ddbfac65/src/main.rs#L215-L217, duplicates…

they should all redirect to the "actual" link

**Comment by Daniel-Valentine** [comment]
[src/main.rs:292](https://github.com/ferritreader/ferrit/blob/8b1d6e8a499fa20cc89bd3809902c761ed82b03f/src/main.rs#L292) is what accepts `/:id_post` and renders a post.

https://github.com/ferritreader/ferrit/blob/8b1d6e8a499fa20cc89bd3809902c761ed82b03f/src/main.rs#L288-L295

Seems like it should be straightforward to change that handler for that route, along with those for the routes @B0pol gave in https://github.com/ferritreader/ferrit/issues/38#issuecomment-1279776324, to `utils::redirect`.

**Comment by Daniel-Valentine** [comment]
A PR is opened with code to implement a redirect from `/:id` to its canonical URL per Reddit.

The curl issue @shruuub saw is something different. What's happening in that case is that curl is making HEAD requests due to the -I flag, but Ferrit is returning 404s since no endpoint handler actually supports HEAD requests. I will address that in another deliverable.

**Comment by shruuub** [comment]
I see, interesting and thanks!

**Comment by Daniel-Valentine** [comment]
The main issue, `/:id` not redirecting to the canonical URL, has been fixed in `401061b` and will make it to v0.1.1. The remaining issues are:

1. responses to HEAD
2. the [other endpoints](https://github.com/ferritreader/ferrit/issues/38#issuecomment-1279776324) that @B0pol identified; because Reddit doesn't provide a redirect to a canonical URL for those like it does for `/:id`, I'm on the fence about doing those, but I'm amenable to it

**Comment by Daniel-Valentine** [comment]
Closing this as completed. The HEAD issue we are tracking under libreddit/libreddit#616.
